### ISSUE TITLE
Storage in use reported by app is different than reported by OS

### ISSUE THREAD

**Issue by LantashTheTokra** [z-huang/music#1039]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. I downloaded all the music playlists I made on youtube. My channel: [https://music.youtube.com/channel/UCmw3aWMGF38XLM67G0cbJhQ](https://music.youtube.com/channel/UCmw3aWMGF38XLM67G0cbJhQ) 
2. I compared the storage values.

### Expected behavior

The sum of the song cache and the image cache should roughly equal the user data.

### Actual behavior

The OS reported 2 GB more than the app.

### Screenshots/Screen recordings

![Screenshot_20230906-214824](https://github.com/z-huang/InnerTune/assets/84555704/bdd61dc9-03c2-43be-b90f-4bcc0465361b)
![Screenshot_20230906-214809](https://github.com/z-huang/InnerTune/assets/84555704/4f802156-91d0-46f4-81a4-a075db4c7055)

### InnerTune version

0.5.2

### Android version

Android 13 (GrapheneOS)

**Comment by sanyoog** [comment]
Aha same issue, it seems like it takes twice the space

**Comment by z-huang** [comment]
If you downloaded songs before v0.5.0 and upgrade to v0.5.x, you may have this issue. That's because there's a new download system since v0.5.0, and your previously downloaded songs won't be recognized by the app settings. To fix it, do a backup, clear app data, and restore your backup.
If you're using the full version, translation models will be downloaded to use lyrics translation. The app won't show the translation model size, so you have to put that into calculation to get the full storage used by the app.

**Comment by LantashTheTokra** [comment]
![Screenshot_20230908-150150](https://github.com/z-huang/InnerTune/assets/84555704/7e88ba55-9999-4871-8c31-3bd6fef1adc6)
![Screenshot_20230908-150140](https://github.com/z-huang/InnerTune/assets/84555704/ff813fd9-025c-40b1-b495-ff97f3d91aeb)
That didn't fix it.
