### ISSUE TITLE
Unable to run (on phone and emulator) latest debug apk from Actions

### ISSUE THREAD

**Issue by netrunner-exe** [z-huang/music#1223]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Download **app.zip** from Actions and extract `app-full-debug.apk`
2. Install
3. Run

### Expected behavior

Working debug apk.

### Actual behavior

When the apk downloaded from Actions is run, an error occurs (indicated in the logs)

### Logs

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zionhuang.music.debug/com.zionhuang.music.MainActivity}: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.zionhuang.music.debug. Make sure to call FirebaseApp.initializeApp(Context) first.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3897)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4043)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2437)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8294)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.zionhuang.music.debug. Make sure to call FirebaseApp.initializeApp(Context) first.
	at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:179)
	at com.google.firebase.remoteconfig.FirebaseRemoteConfig.getInstance(FirebaseRemoteConfig.java:80)
	at com.google.firebase.remoteconfig.ktx.RemoteConfigKt.getRemoteConfig(RemoteConfig.kt:37)
	at com.zionhuang.music.utils.UtilsKt.setupRemoteConfig(Utils.kt:14)
	at com.zionhuang.music.MainActivity.onCreate(MainActivity.kt:153)
	at android.app.Activity.performCreate(Activity.java:8538)
	at android.app.Activity.performCreate(Activity.java:8502)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1437)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3878)
	... 12 more
```

### InnerTune version

Latest debug

### Android version

Android 13

**Comment by ecv80** [comment]
Same. I have tried several debug builds from Actions since the Youtube login error and they all crash with a Firebase error complaining about not being initialized.

Should reopen this bug. 

`11-29 20:17:33.362 22814 22814 E AndroidRuntime: FATAL EXCEPTION: main                          11-29 20:17:33.362 22814 22814 E AndroidRuntime: Process: com.zionhuang.music.debug, PID: 22814 11-29 20:17:33.362 22814 22814 E AndroidRuntime: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.zionhuang.music.debug. Make sure to call FirebaseApp.initializeApp(Context) first.                 11-29 20:17:33.362 22814 22814 E AndroidRuntime:        at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:179)                    11-29 20:17:33.362 22814 22814 E AndroidRuntime:        at com.google.firebase.crashlytics.FirebaseCrashlytics.getInstance(FirebaseCrashlytics.java:213)                                        11-29 20:17:33.362 22814 22814 E AndroidRuntime:        at com.google.firebase.crashlytics.ktx.FirebaseCrashlyticsKt.getCrashlytics(FirebaseCrashlytics.kt:38)                                  11-29 20:17:33.362 22814 22814 E AndroidRuntime:        at com.zionhuang.music.utils.UtilsKt.reportException(Utils.kt:7)                        11-29 20:17:33.362 22814 22814 E AndroidRuntime:        at com.zionhuang.music.playback.PlayerConnection.onPlayerErrorChanged(PlayerConnection.kt:177)                                          11-29 20:17:33.362 22814 22814 E AndroidRuntime:        at androidx.media3.exoplayer.ExoPlayerImpl.lambda$updatePlaybackInfo$15(ExoPlayerImpl.java:2115)                                        11-29 20:17:33.362 22814 22814 E AndroidRuntime:        at androidx.media3.exoplayer.ExoPlayerImpl$$ExternalSyntheticLambda25.invoke(D8$$SyntheticClass:0)                                      11-29 20:17:33.362 22814 22814 E AndroidRuntime:        at androidx.media3.common.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:339)  11-29 20:17:33.362 22814 22814 E AndroidRuntime:        at androidx.media3.common.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:223)    11-29 20:17:33.362 22814 22814 E AndroidRuntime:        at androidx.media3.common.util.ListenerSet$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)                                          11-29 20:17:33.362 22814 22814 E AndroidRuntime:        at androidx.media3.common.util.ListenerSet.flushEvents(ListenerSet.java:245)            11-29 20:17:33.362 22814 22814 E AndroidRuntime:        at androidx.media3.exoplayer.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:2182)  11-29 20:17:33.362 22814 22814 E AndroidRuntime:        at androidx.media3.exoplayer.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:2016)  11-29 20:17:33.362 22814 22814 E AndroidRuntime:        at androidx.media3.exoplayer.ExoPlayerImpl.lambda$new$1$androidx-media3-exoplayer-ExoPlayerImpl(ExoPlayerImpl.java:351)                 11-29 20:17:33.362 22814 22814 E AndroidRuntime:        at androidx.media3.exoplayer.ExoPlayerImpl$$ExternalSyntheticLambda10.run(D8$$SyntheticClass:0)                                         11-29 20:17:33.362 22814 22814 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:942)                                  11-29 20:17:33.362 22814 22814 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)                                  11-29 20:17:33.362 22814 22814 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)                                          11-29 20:17:33.362 22814 22814 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)                                              11-29 20:17:33.362 22814 22814 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7924)                            11-29 20:17:33.362 22814 22814 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)                                       11-29 20:17:33.362 22814 22814 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)    11-29 20:17:33.362 22814 22814 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)`
