### ISSUE TITLE
Cooperate with Malopieds in one repo

### ISSUE THREAD

**Issue by gechoto** [z-huang/music#1338]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

It is confusing for users to have two separate versions.
Maybe ask @Malopieds if he wants to join this repo and help maintain it?

### Why do you want this feature?

- have only one version of InnerTune
- not having to switch between this and a fork in cases you (main dev) lack time
- less stress for you

**Comment by Malopieds** [comment]
> It is confusing for users to have two separate versions.

Yes we've seen before people confusing about those forks. That's why I planned to rename mine, and also change the logo to avoid that. Of course there will still be confusion I guess but less.

> Maybe ask @Malopieds if he wants to join this repo and help maintain it?

I could maintain **some** part of it. Z-huang made it clear that some of mine changes will NOT be part of his work, which is totally understandable, we have different vision and that's what makes a world. But yet, the help I would give would have to be first approved by z-huang, I don't want to force some changes here without their approval. I can still do it for some critical changes maybe, like we've seen 3 month ago approx. but I think this is pretty rare.

I will let z-huang answer for their part but I think, it's maybe good for all of us to keep things separate!

**Comment by z-huang** [comment]
I have the same idea with @Malopieds. Everyone has its own taste. Different repos have different style, and users can choose the one they like. Since our codebases are similar, we can cooperate on bug fixes. Finding bugs alone is sometimes hard. Having multiple developers working on it improves efficiency and delivers better experience to users.
