### ISSUE TITLE
 In-App Update Feature

### ISSUE THREAD

**Issue by Aditya1Jhaveri** [z-huang/music#1344]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Description:
Currently, users are directed to GitHub to download the latest APK for updates, which can be Inconvenient. I propose adding an in-app update feature that checks for the latest release on GitHub and automatically updates the app without requiring the user to navigate away from the app.

### Why do you want this feature?

I want this feature because it would simplify the update process, especially for non-technical users. For them, going to GitHub to manually download and install the latest APK can be complicated. An in-app update feature would make it easier for all users to stay on the latest version, improving the overall user experience.

**Comment by z-huang** [comment]
I don't want to maintain an in-app updater. Only an update checker is enough.
In fact, in-app updater was added before, but I removed it because it's a hassle to download and install apk. All this can be done by user in a few clicks. This is not a focus of a music player.
Also, there are tools to handle it, such as https://github.com/ImranR98/Obtainium.
