### ISSUE TITLE
Some Song Can't Be Played

### ISSUE THREAD

**Issue by hantu152** [z-huang/music#1442]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

when i played a song, it didn't play and show text "Timeout"
the song called All Fucked Up by The Amity Affliction

### Expected behavior

it should be played

### Actual behavior

but it didn't play and show text "Timeout"

### Screenshots/Screen recordings

![Screenshot_20240822-233639](https://github.com/user-attachments/assets/1c6305a8-7137-40be-a896-9169e1e768d3)

### Logs

Not able to get it.

### InnerTune version

0.5.8

### Android version

Android 10

**Comment by stephnradd** [comment]
I had this problem too
There are 2 song that can't be played as of now
1. If I Was Your Girlfriend (ft. Lucy) - Mondays
2. Nobody Compares - One Direction[
![Screenshot_20240823-224346_InnerTune](https://github.com/user-attachments/assets/5636396e-a242-48f0-9c34-fc4bb531ad62)
](url)

**Comment by z-huang** [comment]
"All Fucked Up by The Amity Affliction" cannot be played because it's age restricted. Even with some tricks I cannot find the streams.
"If I Was Your Girlfriend (ft. Lucy)" and "Nobody Compares - One Direction": I can play them normally. Can you try this for me: clear app data and play again. Of course remember to backup your data.

**Comment by hantu152** [comment]
ouch.. thanks for the respond, its kinda sad to know😔.

**Comment by stephnradd** [comment]
> "All Fucked Up by The Amity Affliction" cannot be played because it's age restricted. Even with some tricks I cannot find the streams. "If I Was Your Girlfriend (ft. Lucy)" and "Nobody Compares - One Direction": I can play them normally. Can you try this for me: clear app data and play again. Of course remember to backup your data.

no luck, now even MORE SONGS can't be played

I have a playlist containing 66 song, ONLY 28 OF THEM that can be played, smh.
![Screenshot_20240829-092036_InnerTune](https://github.com/user-attachments/assets/852961ba-4945-45e9-8a64-f6ba3a535df9)
![Screenshot_20240829-092057_InnerTune](https://github.com/user-attachments/assets/1f13743b-2d85-47a4-a5fb-5aea77881d55)

**Comment by z-huang** [comment]
Can you help me do an experiment? Clear app data and try whether the two song can play. Make sure to do a backup!

**Comment by MontyJavaScript** [comment]
> Can you help me do an experiment? Clear app data and try whether the two song can play. Make sure to do a backup!

Because the other guy didn't respond I'm gonna do the test myself, I tested it with 2 songs I have the "No Stream Avalible" error with ("Xanadu (Extended Version)" which is 4:44 minutes and "I Burn (feat. Casey Lee Williams & Lamar Hall)" which is 3:11)

I cleared the app data by going to the apps settings, going to the storage menu, and pressing "clear storage"

Test 1:
-Cleared App data
-Played under a minute of "I Burn"
-Restore backup
-Song can still play in its entirety

Test 2:
-Cleared App data
-Restored Backup
-attempt to play "Xanadu EV"
-No Stream Avalible error

Test 3:
-Cleared App data
-played a few seconds of Xanadu EV
-Restored backup
-Xanadu EV plays, but then it got the error again at 1:34
![Screenshot_20240908-192852](https://github.com/user-attachments/assets/26047dc0-ffc3-4dd7-b583-2c29af6ef7ff)

If I close Xanadu EV and play it again, it still only plays to 1:34, however, if I try to move the slider to 1:10 or more, it pulls up the same error, if I put the slider at 1:09 or below, it will continue playing until it hits 1:34 again

Test 4:
-Cleared App data
-played a minute of Xanadu EV
-Restored backup
-Xanadu EV plays, but then it got the error again further into the song

Test 5:
-Cleared App data
-played the entirety of Xanadu EV (4:44)
-Restored backup
-Xanadu EV plays all the way through now

If you need any more experiments, I have at least 4 other songs ("Misery Business", "Devils Never Cry HR/HM Ver. (Devil May Cry 5 SE Edit)", "Good Girl Gone Bad", and " I CAN'T STOP ME (English Ver.)") that have the same error

**Comment by stephnradd** [comment]
> Can you help me do an experiment? Clear app data and try whether the two song can play. Make sure to do a backup!

Sorry for late reply 
I did your suggestions, and those 2 songs will play if I DON'T RESTORE MY BACKUP. If I restore it, the song won't play!

![Screenshot_20240909-152151_InnerTune](https://github.com/user-attachments/assets/d658d4f9-b18c-49a0-814c-c3e7e84d9dba)
