### ISSUE TITLE
Songs From Youtube Music (Actually) are not Downloaded

### ISSUE THREAD

**Issue by X-Gorn** [z-huang/music#197]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

After i downloaded a music from youtube music, i tried to turn of my wi-fi/mobile data and i realize that the music from youtube music aren't downloaded

### Expected behavior

The music are downloadable and can be played when there's no internet connection

### Actual behavior

The music aren't downloadable and can't be played when there's no internet connection

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/67302057/191344390-41347c49-d315-43e4-9cf6-90df2264e410.mp4

### Music version

0.4.0

### Android version

Android 12

**Comment by owencz1998** [comment]
Im able to listen offline but this almost looks like the issue that's happened before I think it's android system that's deleting the files I could be completely wrong but the way its behaving is exactly like it I dunno if he needs to add storage permissions due to android always changing or if he can make something for this to work annoying thing is he did fix this and so far it hasn't happened to me since only issue I have with downloads is its very very slow and sometimes takes a while for the next song to start downloading.

**Comment by owencz1998** [comment]
Have u tried to delete download and then redownload and wait for the tick to show before turning network off

**Comment by X-Gorn** [comment]
nope, i've tried to delete and redownload but it's still the same

**Comment by owencz1998** [comment]
@z-huang  also coukd it be storage permissions as iv seen a lot about if you don't allow it downloads and other things won't be read maybe for other devices or is it really not necessary

**Comment by X-Gorn** [comment]
@z-huang this time it's downloaded and the files is increased, also the song is playable, maybe earlier it was an internet connection error
thanks, i'll close this issue.

**Comment by owencz1998** [comment]
No worries dude
