### ISSUE TITLE
Manual sort

### ISSUE THREAD

**Issue by airon90** [z-huang/music#21]
I'd like to manually sort songs, playlists and artists

**Comment by z-huang** [comment]
Why not create a playlist and put the songs in your preferred order?

Just like other music apps, there's no option for manually sorting all songs, artists and playlists. That's because in these sections, users are "finding" the items to browse into or play. Sorting by name or create date and a search function will be enough. The only thing that needs to be manually sorted is your playlist songs, which affect the order of the songs you're listening to. So, I think manual sort isn't mandatory.

**Comment by airon90** [comment]
> Why not create a playlist and put the songs in your preferred order?

You are right. I maybe should close this issue and open another one to better explain the question: as of now, you add songs and you can filter them by name (by searching them) and by author (by using the Artists page). I don't like to have songs by author in default modes (by name or by added date): I'd like to have songs about an artist ordered by album.

Right now I create custom lists but I'd like to play songs by album in an easier way :)

**Comment by z-huang** [comment]
If I create an "Albums" section in the bottom navigation bar, does that help?This will correspond to YT Music's album. However, this needs a modification of NewPipe Extractor, so it will take more time.

**Comment by airon90** [comment]
I imagined another section inside Artists page, where you can directly select artist's album(s), where you can navigate through the album or select albums to create a playlist, or a "All" section, where you get all tracks by the artist.

If you install [Vanilla Music](https://vanilla-music.github.io/) you understand what I mean

> This will correspond to YT Music's album

Never used YT Music so I don't know what you mean, sorry

**Comment by z-huang** [comment]
I have an idea. In the artists page, when an artist is clicked, it goes to a new page showing the artist's details, where the artist's albums, songs are listed. [Oto Music](https://play.google.com/store/apps/details?id=com.piyush.music) has the UI that I like.

> This will correspond to YT Music's album

The app will get information about an artist's albums by YT Music API, so users won't need to create them manually.
