### ISSUE TITLE
Add "Delete" button for artists

### ISSUE THREAD

**Issue by xmha97** [z-huang/music#245]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

![Screenshot_2022-09-28-06-03-45-504_com zionhuang music](https://user-images.githubusercontent.com/23485114/192674869-d2eb5f8c-3e7f-4695-a015-f7d86967f668.jpg)

### Why do you want this feature?

Delete all songs from a artist

**Comment by z-huang** [comment]
I'm not doing this feature because it's complicated to delete an artist. An artist may be related to an album with multiple artists. If you delete the artist, should the album be deleted as well? This is not good. The same conflict occurs when deleting a song. Should the album of the song be deleted as well? Therefore, my decision is:
1. Album songs cannot be deleted. You can only delete the album and delete all the album songs.
2. Artists can be deleted. They will be automatically deleted if they have no song.
