### ISSUE TITLE
Dark Mode issue

### ISSUE THREAD

**Issue by dhishkyaon** [z-huang/music#69]
When Dark Mode is enabled -

![Screenshot_20220601-074451.png](https://user-images.githubusercontent.com/88529066/171314470-12906bea-9d8a-4bf7-b54a-1384631a4720.png)![Screenshot_20220601-074145.png](https://user-images.githubusercontent.com/88529066/171314485-a1b68d5e-2047-4356-a383-cb0b2851b072.png)

DEVICE - PIXEL 4a, ANDROID 12L

**Comment by z-huang** [comment]
Can changing the dark mode settings solve the text color?

**Comment by z-huang** [comment]
@dhishkyaon Can you try this version 4ce54badd697383f10f7c5a2148cc7d59bc9a706 on Pixel? I've tested OneUI on Android 10 and it works well.

**Comment by dhishkyaon** [comment]
i don't know how to build from source. If you can provide me .apk file then i can test it out :-)

**Comment by airon90** [comment]
@dhishkyaon Go in Actions, select the "[Fix] Dark theme" commit, in the lower section named Artifacts select "app". You can press [here](https://github.com/z-huang/music/suites/6791426489/artifacts/260468738) as I did this for you. You will download a zip file containing an apk file you have to install so that you can test this app up to that commit

**Comment by dhishkyaon** [comment]
its working
