### ISSUE TITLE
Download entire playlist

### ISSUE THREAD

**Issue by Alliba** [z-huang/music#8]
Hi Bro,
a really cool APP.
Is there any way to support you (financially?....)

Still have 2 suggestions for improvement: There should be a kind of backup in which you can save the app settings and in which the created playlists and added songs to library. 
If you change your phone, you could simply restore the file and you would not have the work of adding the playlists and songs again.
2. in the playlists could also be added a button to download the entire playlist.

Maybe in the next updates feasible?

**Comment by z-huang** [comment]
Got it. I'll add them to the roadmap. The actual time for the update is not assured, because the first suggestion will take some time to be completed.
As for support, this app is my side project, and I'm doing this with pleasure. If the project become stable and mature, I'll consider putting donation information in `README.md`.

**Comment by airon90** [comment]
Backup BR is now available in #57 so this BR is about downloading entire playlists. Somebody should rename this BR @Alliba @z-huang
